steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/sahil1005/classfier-k8s.git']

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=app-env-configmap
  - --location=${_ZONE}
  - --cluster=${_GKE_CLUSTER}  



  # build the container image modelserver
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${_PROJECT}/modelserver:${_VERSION}", "./modelserver"]
  # push container image modelserver
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${_PROJECT}/modelserver:${_VERSION}"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=modelserver
  - --image=gcr.io/${_PROJECT}/modelserver:${_VERSION}
  - --location=${_ZONE}
  - --cluster=${_GKE_CLUSTER}


  # build the container image webserver
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${_PROJECT}/webserver:${_VERSION}", "./webserver"]
  # push container image webserver
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${_PROJECT}/webserver:${_VERSION}"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=webserver
  - --image=gcr.io/${_PROJECT}/webserver:${_VERSION}
  - --location=${_ZONE}
  - --cluster=${_GKE_CLUSTER}  

substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: ppedetonline
    _ZONE: asia-south1-a
    _GKE_CLUSTER: ppedetonline-cluster  

    # Developers ONLY change
    _VERSION: v1.0  