steps:

- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/sahil1005/classfier-k8s.git']

  # build the container image modelserver
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${_PROJECT}/modelserver:${_VERSION}", "./modelserver"]
  # push container image modelserver
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${_PROJECT}/modelserver:${_VERSION}"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - 'set'
  - 'image'
  - 'deployment/modelserver-deployment'
  - 'modelserver=gcr.io/${_PROJECT}/modelserver:${_VERSION}'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'


  # build the container image webserver
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${_PROJECT}/webserver:${_VERSION}", "./webserver"]
  # push container image webserver
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${_PROJECT}/webserver:${_VERSION}"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - 'set'
  - 'image'
  - 'deployment/webserver-deployment'
  - 'webserver=gcr.io/${_PROJECT}/webserver:${_VERSION}'
  env:
    -  'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}' 

substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: ppedetonline-340207
    _ZONE: asia-south1-a
    _GKE_CLUSTER: ppedetonline-cluster  

    # Developers ONLY change
    _VERSION: v1.0  